package database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "DATE".
 */
@Entity
public class Date {

    @Id(autoincrement = true)
    private Long id;
    private int day_number;
    private Long week_id;
    private Boolean locked;
    private Integer progress;

    @Generated(hash = 753683215)
    public Date() {
    }

    public Date(Long id) {
        this.id = id;
    }

    @Generated(hash = 951619636)
    public Date(Long id, int day_number, Long week_id, Boolean locked, Integer progress) {
        this.id = id;
        this.day_number = day_number;
        this.week_id = week_id;
        this.locked = locked;
        this.progress = progress;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getDay_number() {
        return day_number;
    }

    public void setDay_number(int day_number) {
        this.day_number = day_number;
    }

    public Long getWeek_id() {
        return week_id;
    }

    public void setWeek_id(Long week_id) {
        this.week_id = week_id;
    }

    public Boolean getLocked() {
        return locked;
    }

    public void setLocked(Boolean locked) {
        this.locked = locked;
    }

    public Integer getProgress() {
        return progress;
    }

    public void setProgress(Integer progress) {
        this.progress = progress;
    }

}
