package database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "GENERAL".
 */
@Entity
public class General {

    @Id(autoincrement = true)
    private Long id;
    private Integer general_progress;
    private Long current_active_date_id;
    private Long current_active_week_id;

    @Generated(hash = 1493688139)
    public General() {
    }

    public General(Long id) {
        this.id = id;
    }

    @Generated(hash = 1906430483)
    public General(Long id, Integer general_progress, Long current_active_date_id, Long current_active_week_id) {
        this.id = id;
        this.general_progress = general_progress;
        this.current_active_date_id = current_active_date_id;
        this.current_active_week_id = current_active_week_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getGeneral_progress() {
        return general_progress;
    }

    public void setGeneral_progress(Integer general_progress) {
        this.general_progress = general_progress;
    }

    public Long getCurrent_active_date_id() {
        return current_active_date_id;
    }

    public void setCurrent_active_date_id(Long current_active_date_id) {
        this.current_active_date_id = current_active_date_id;
    }

    public Long getCurrent_active_week_id() {
        return current_active_week_id;
    }

    public void setCurrent_active_week_id(Long current_active_week_id) {
        this.current_active_week_id = current_active_week_id;
    }

}
