package database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "IDIOM".
 */
@Entity
public class Idiom {

    @Id(autoincrement = true)
    private Long id;
    private String idiom_eng;
    private String idiom_per;
    private String idiom_example_eng;
    private String idiom_example_per;
    private Long date_id;

    @Generated(hash = 1459594445)
    public Idiom() {
    }

    public Idiom(Long id) {
        this.id = id;
    }

    @Generated(hash = 1472743060)
    public Idiom(Long id, String idiom_eng, String idiom_per, String idiom_example_eng, String idiom_example_per, Long date_id) {
        this.id = id;
        this.idiom_eng = idiom_eng;
        this.idiom_per = idiom_per;
        this.idiom_example_eng = idiom_example_eng;
        this.idiom_example_per = idiom_example_per;
        this.date_id = date_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getIdiom_eng() {
        return idiom_eng;
    }

    public void setIdiom_eng(String idiom_eng) {
        this.idiom_eng = idiom_eng;
    }

    public String getIdiom_per() {
        return idiom_per;
    }

    public void setIdiom_per(String idiom_per) {
        this.idiom_per = idiom_per;
    }

    public String getIdiom_example_eng() {
        return idiom_example_eng;
    }

    public void setIdiom_example_eng(String idiom_example_eng) {
        this.idiom_example_eng = idiom_example_eng;
    }

    public String getIdiom_example_per() {
        return idiom_example_per;
    }

    public void setIdiom_example_per(String idiom_example_per) {
        this.idiom_example_per = idiom_example_per;
    }

    public Long getDate_id() {
        return date_id;
    }

    public void setDate_id(Long date_id) {
        this.date_id = date_id;
    }

}
