package database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "MAIN_CONTEXT".
 */
@Entity
public class MainContext {

    @Id(autoincrement = true)
    private Long id;
    private long date_id;
    private String title_eng;
    private String title_per;
    private String context_eng;
    private String context_per;

    @Generated(hash = 1161059903)
    public MainContext() {
    }

    public MainContext(Long id) {
        this.id = id;
    }

    @Generated(hash = 1878605119)
    public MainContext(Long id, long date_id, String title_eng, String title_per, String context_eng, String context_per) {
        this.id = id;
        this.date_id = date_id;
        this.title_eng = title_eng;
        this.title_per = title_per;
        this.context_eng = context_eng;
        this.context_per = context_per;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getDate_id() {
        return date_id;
    }

    public void setDate_id(long date_id) {
        this.date_id = date_id;
    }

    public String getTitle_eng() {
        return title_eng;
    }

    public void setTitle_eng(String title_eng) {
        this.title_eng = title_eng;
    }

    public String getTitle_per() {
        return title_per;
    }

    public void setTitle_per(String title_per) {
        this.title_per = title_per;
    }

    public String getContext_eng() {
        return context_eng;
    }

    public void setContext_eng(String context_eng) {
        this.context_eng = context_eng;
    }

    public String getContext_per() {
        return context_per;
    }

    public void setContext_per(String context_per) {
        this.context_per = context_per;
    }

}
