package database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "PRONUNCIATION".
 */
@Entity
public class Pronunciation {

    @Id(autoincrement = true)
    private Long id;
    private long word_id;
    private String file_name;

    @Generated(hash = 1134034502)
    public Pronunciation() {
    }

    public Pronunciation(Long id) {
        this.id = id;
    }

    @Generated(hash = 455010050)
    public Pronunciation(Long id, long word_id, String file_name) {
        this.id = id;
        this.word_id = word_id;
        this.file_name = file_name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getWord_id() {
        return word_id;
    }

    public void setWord_id(long word_id) {
        this.word_id = word_id;
    }

    public String getFile_name() {
        return file_name;
    }

    public void setFile_name(String file_name) {
        this.file_name = file_name;
    }

}
