package database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "REVIEW".
 */
@Entity
public class Review {

    @Id(autoincrement = true)
    private Long id;
    private long week_id;
    private Long date_id;
    private String word;
    private String definition;

    @Generated(hash = 2008964488)
    public Review() {
    }

    public Review(Long id) {
        this.id = id;
    }

    @Generated(hash = 1925712027)
    public Review(Long id, long week_id, Long date_id, String word, String definition) {
        this.id = id;
        this.week_id = week_id;
        this.date_id = date_id;
        this.word = word;
        this.definition = definition;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getWeek_id() {
        return week_id;
    }

    public void setWeek_id(long week_id) {
        this.week_id = week_id;
    }

    public Long getDate_id() {
        return date_id;
    }

    public void setDate_id(Long date_id) {
        this.date_id = date_id;
    }

    public String getWord() {
        return word;
    }

    public void setWord(String word) {
        this.word = word;
    }

    public String getDefinition() {
        return definition;
    }

    public void setDefinition(String definition) {
        this.definition = definition;
    }

}
