package database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "SENTENCE".
 */
@Entity
public class Sentence {

    @Id(autoincrement = true)
    private Long id;
    private long word_id;
    private String sentence_eng;
    private String sentence_per;
    private String pronunciation_file_address;
    private String deleted_word;

    @Generated(hash = 300356185)
    public Sentence() {
    }

    public Sentence(Long id) {
        this.id = id;
    }

    @Generated(hash = 592832698)
    public Sentence(Long id, long word_id, String sentence_eng, String sentence_per, String pronunciation_file_address, String deleted_word) {
        this.id = id;
        this.word_id = word_id;
        this.sentence_eng = sentence_eng;
        this.sentence_per = sentence_per;
        this.pronunciation_file_address = pronunciation_file_address;
        this.deleted_word = deleted_word;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getWord_id() {
        return word_id;
    }

    public void setWord_id(long word_id) {
        this.word_id = word_id;
    }

    public String getSentence_eng() {
        return sentence_eng;
    }

    public void setSentence_eng(String sentence_eng) {
        this.sentence_eng = sentence_eng;
    }

    public String getSentence_per() {
        return sentence_per;
    }

    public void setSentence_per(String sentence_per) {
        this.sentence_per = sentence_per;
    }

    public String getPronunciation_file_address() {
        return pronunciation_file_address;
    }

    public void setPronunciation_file_address(String pronunciation_file_address) {
        this.pronunciation_file_address = pronunciation_file_address;
    }

    public String getDeleted_word() {
        return deleted_word;
    }

    public void setDeleted_word(String deleted_word) {
        this.deleted_word = deleted_word;
    }

}
