package database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "USER_ADDED_VOCABULARY".
 */
@Entity
public class UserAddedVocabulary {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    private String word_eng;

    @NotNull
    private String word_per;
    private String example;
    private String image_address;
    private int stage;
    private long date_id;
    private long word_id;
    private long last_reviewed_time;

    @Generated(hash = 760605544)
    public UserAddedVocabulary() {
    }

    public UserAddedVocabulary(Long id) {
        this.id = id;
    }

    @Generated(hash = 492840432)
    public UserAddedVocabulary(Long id, @NotNull String word_eng, @NotNull String word_per, String example, String image_address, int stage, long date_id, long word_id,
            long last_reviewed_time) {
        this.id = id;
        this.word_eng = word_eng;
        this.word_per = word_per;
        this.example = example;
        this.image_address = image_address;
        this.stage = stage;
        this.date_id = date_id;
        this.word_id = word_id;
        this.last_reviewed_time = last_reviewed_time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getWord_eng() {
        return word_eng;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setWord_eng(@NotNull String word_eng) {
        this.word_eng = word_eng;
    }

    @NotNull
    public String getWord_per() {
        return word_per;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setWord_per(@NotNull String word_per) {
        this.word_per = word_per;
    }

    public String getExample() {
        return example;
    }

    public void setExample(String example) {
        this.example = example;
    }

    public String getImage_address() {
        return image_address;
    }

    public void setImage_address(String image_address) {
        this.image_address = image_address;
    }

    public int getStage() {
        return stage;
    }

    public void setStage(int stage) {
        this.stage = stage;
    }

    public long getDate_id() {
        return date_id;
    }

    public void setDate_id(long date_id) {
        this.date_id = date_id;
    }

    public long getWord_id() {
        return word_id;
    }

    public void setWord_id(long word_id) {
        this.word_id = word_id;
    }

    public long getLast_reviewed_time() {
        return last_reviewed_time;
    }

    public void setLast_reviewed_time(long last_reviewed_time) {
        this.last_reviewed_time = last_reviewed_time;
    }

}
