package database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "USER_RECORD".
 */
@Entity
public class UserRecord {

    @Id(autoincrement = true)
    private Long id;
    private long word_id;
    private long date_id;
    private Boolean is_speaking;
    private Boolean is_reading;
    private Boolean is_writing;
    private Boolean is_listening;
    private Boolean score;

    @Generated(hash = 646705062)
    public UserRecord() {
    }

    public UserRecord(Long id) {
        this.id = id;
    }

    @Generated(hash = 1834807237)
    public UserRecord(Long id, long word_id, long date_id, Boolean is_speaking, Boolean is_reading, Boolean is_writing, Boolean is_listening, Boolean score) {
        this.id = id;
        this.word_id = word_id;
        this.date_id = date_id;
        this.is_speaking = is_speaking;
        this.is_reading = is_reading;
        this.is_writing = is_writing;
        this.is_listening = is_listening;
        this.score = score;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getWord_id() {
        return word_id;
    }

    public void setWord_id(long word_id) {
        this.word_id = word_id;
    }

    public long getDate_id() {
        return date_id;
    }

    public void setDate_id(long date_id) {
        this.date_id = date_id;
    }

    public Boolean getIs_speaking() {
        return is_speaking;
    }

    public void setIs_speaking(Boolean is_speaking) {
        this.is_speaking = is_speaking;
    }

    public Boolean getIs_reading() {
        return is_reading;
    }

    public void setIs_reading(Boolean is_reading) {
        this.is_reading = is_reading;
    }

    public Boolean getIs_writing() {
        return is_writing;
    }

    public void setIs_writing(Boolean is_writing) {
        this.is_writing = is_writing;
    }

    public Boolean getIs_listening() {
        return is_listening;
    }

    public void setIs_listening(Boolean is_listening) {
        this.is_listening = is_listening;
    }

    public Boolean getScore() {
        return score;
    }

    public void setScore(Boolean score) {
        this.score = score;
    }

}
