package database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "WEEK".
 */
@Entity
public class Week {

    @Id(autoincrement = true)
    private Long id;
    private int week_number;
    private int progress;
    private Boolean locked;
    private Integer rate;

    @Generated(hash = 2135529658)
    public Week() {
    }

    public Week(Long id) {
        this.id = id;
    }

    @Generated(hash = 1837416810)
    public Week(Long id, int week_number, int progress, Boolean locked, Integer rate) {
        this.id = id;
        this.week_number = week_number;
        this.progress = progress;
        this.locked = locked;
        this.rate = rate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getWeek_number() {
        return week_number;
    }

    public void setWeek_number(int week_number) {
        this.week_number = week_number;
    }

    public int getProgress() {
        return progress;
    }

    public void setProgress(int progress) {
        this.progress = progress;
    }

    public Boolean getLocked() {
        return locked;
    }

    public void setLocked(Boolean locked) {
        this.locked = locked;
    }

    public Integer getRate() {
        return rate;
    }

    public void setRate(Integer rate) {
        this.rate = rate;
    }

}
