package database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "WORD_FORM".
 */
@Entity
public class WordForm {

    @Id(autoincrement = true)
    private Long id;
    private long word_id;
    private Boolean is_noun;
    private Boolean is_adv;
    private Boolean is_adj;
    private Boolean is_verb;
    private String word;
    private String pronunciation_file_address;

    @Generated(hash = 1121703128)
    public WordForm() {
    }

    public WordForm(Long id) {
        this.id = id;
    }

    @Generated(hash = 1928594059)
    public WordForm(Long id, long word_id, Boolean is_noun, Boolean is_adv, Boolean is_adj, Boolean is_verb, String word, String pronunciation_file_address) {
        this.id = id;
        this.word_id = word_id;
        this.is_noun = is_noun;
        this.is_adv = is_adv;
        this.is_adj = is_adj;
        this.is_verb = is_verb;
        this.word = word;
        this.pronunciation_file_address = pronunciation_file_address;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getWord_id() {
        return word_id;
    }

    public void setWord_id(long word_id) {
        this.word_id = word_id;
    }

    public Boolean getIs_noun() {
        return is_noun;
    }

    public void setIs_noun(Boolean is_noun) {
        this.is_noun = is_noun;
    }

    public Boolean getIs_adv() {
        return is_adv;
    }

    public void setIs_adv(Boolean is_adv) {
        this.is_adv = is_adv;
    }

    public Boolean getIs_adj() {
        return is_adj;
    }

    public void setIs_adj(Boolean is_adj) {
        this.is_adj = is_adj;
    }

    public Boolean getIs_verb() {
        return is_verb;
    }

    public void setIs_verb(Boolean is_verb) {
        this.is_verb = is_verb;
    }

    public String getWord() {
        return word;
    }

    public void setWord(String word) {
        this.word = word;
    }

    public String getPronunciation_file_address() {
        return pronunciation_file_address;
    }

    public void setPronunciation_file_address(String pronunciation_file_address) {
        this.pronunciation_file_address = pronunciation_file_address;
    }

}
