package database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "WORD".
 */
@Entity
public class Word {

    @Id(autoincrement = true)
    private Long id;
    private long week_id;
    private long date_id;
    private String word;
    private String per_def;
    private String eng_def;

    @Generated(hash = 3342184)
    public Word() {
    }

    public Word(Long id) {
        this.id = id;
    }

    @Generated(hash = 1384401055)
    public Word(Long id, long week_id, long date_id, String word, String per_def, String eng_def) {
        this.id = id;
        this.week_id = week_id;
        this.date_id = date_id;
        this.word = word;
        this.per_def = per_def;
        this.eng_def = eng_def;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getWeek_id() {
        return week_id;
    }

    public void setWeek_id(long week_id) {
        this.week_id = week_id;
    }

    public long getDate_id() {
        return date_id;
    }

    public void setDate_id(long date_id) {
        this.date_id = date_id;
    }

    public String getWord() {
        return word;
    }

    public void setWord(String word) {
        this.word = word;
    }

    public String getPer_def() {
        return per_def;
    }

    public void setPer_def(String per_def) {
        this.per_def = per_def;
    }

    public String getEng_def() {
        return eng_def;
    }

    public void setEng_def(String eng_def) {
        this.eng_def = eng_def;
    }

}
