package database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "WORD_SEARCH".
 */
@Entity
public class WordSearch {

    @Id(autoincrement = true)
    private Long id;
    private long week_id;
    private Long date_id;
    private Integer paragraph_number;
    private String paragraph_eng;
    private String paragraph_per;

    @Generated(hash = 452889251)
    public WordSearch() {
    }

    public WordSearch(Long id) {
        this.id = id;
    }

    @Generated(hash = 2047647426)
    public WordSearch(Long id, long week_id, Long date_id, Integer paragraph_number, String paragraph_eng, String paragraph_per) {
        this.id = id;
        this.week_id = week_id;
        this.date_id = date_id;
        this.paragraph_number = paragraph_number;
        this.paragraph_eng = paragraph_eng;
        this.paragraph_per = paragraph_per;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getWeek_id() {
        return week_id;
    }

    public void setWeek_id(long week_id) {
        this.week_id = week_id;
    }

    public Long getDate_id() {
        return date_id;
    }

    public void setDate_id(Long date_id) {
        this.date_id = date_id;
    }

    public Integer getParagraph_number() {
        return paragraph_number;
    }

    public void setParagraph_number(Integer paragraph_number) {
        this.paragraph_number = paragraph_number;
    }

    public String getParagraph_eng() {
        return paragraph_eng;
    }

    public void setParagraph_eng(String paragraph_eng) {
        this.paragraph_eng = paragraph_eng;
    }

    public String getParagraph_per() {
        return paragraph_per;
    }

    public void setParagraph_per(String paragraph_per) {
        this.paragraph_per = paragraph_per;
    }

}
