package database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "WORD_SEARCH_DELETED_WORD".
 */
@Entity
public class WordSearchDeletedWord {

    @Id(autoincrement = true)
    private Long id;
    private long word_search_id;
    private Integer paragraph_number;
    private String deleted_word;
    private String hint;

    @Generated(hash = 905868696)
    public WordSearchDeletedWord() {
    }

    public WordSearchDeletedWord(Long id) {
        this.id = id;
    }

    @Generated(hash = 1936597686)
    public WordSearchDeletedWord(Long id, long word_search_id, Integer paragraph_number, String deleted_word, String hint) {
        this.id = id;
        this.word_search_id = word_search_id;
        this.paragraph_number = paragraph_number;
        this.deleted_word = deleted_word;
        this.hint = hint;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getWord_search_id() {
        return word_search_id;
    }

    public void setWord_search_id(long word_search_id) {
        this.word_search_id = word_search_id;
    }

    public Integer getParagraph_number() {
        return paragraph_number;
    }

    public void setParagraph_number(Integer paragraph_number) {
        this.paragraph_number = paragraph_number;
    }

    public String getDeleted_word() {
        return deleted_word;
    }

    public void setDeleted_word(String deleted_word) {
        this.deleted_word = deleted_word;
    }

    public String getHint() {
        return hint;
    }

    public void setHint(String hint) {
        this.hint = hint;
    }

}
